const postStyles = {
  card: {
    display: "flex",
    flexDirection: "column",
    width: "220px",
    height: "235px",
    borderRadius: "15px",
    position: "relative",
    backgroundColor: (theme) => theme.palette?.background?.paper || "#fff",
    overflow: "hidden",
  },
  media: {
    height: "100px",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  overlay: {
    position: "absolute",
    top: "10px",
    left: "10px",
    color: "white",
    zIndex: 1,
    textShadow: "0px 0px 3px rgba(0,0,0,0.6)",
  },
  creatorName: {
    fontSize: "0.8rem",
    fontWeight: "bold",
    lineHeight: 1.2,
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    maxWidth: "120px",
  },
  timeText: {
    fontSize: "0.65rem",
    lineHeight: 1.2,
  },
  overlay2: {
    position: "absolute",
    top: "8px",
    right: "8px",
    color: "white",
    zIndex: 1,
  },
  editButton: {
    color: "white",
    minWidth: "auto",
    padding: "4px",
    backgroundColor: "rgba(0,0,0,0.3)",
    "&:hover": {
      backgroundColor: "rgba(0,0,0,0.5)",
    },
  },
  contentWrapper: {
    padding: "8px 12px",
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
  },
  details: {
    marginBottom: "4px",
    maxHeight: "18px",
    overflow: "hidden",
  },
  tagText: {
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontSize: "0.7rem",
    lineHeight: 1.3,
    color: (theme) => theme.palette?.text?.secondary || "grey",
  },
  title: {
    fontWeight: "bold",
    fontSize: "0.95rem",
    lineHeight: 1.3,
    marginBottom: "4px",
    maxHeight: "40px",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    textOverflow: "ellipsis",
  },
  messageContent: {
    flexGrow: 1,
    overflow: "hidden",
    minHeight: "30px",
    padding: "0 !important",
    marginBottom: "4px",
  },
  messageText: {
    fontSize: "0.75rem",
    lineHeight: 1.4,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    textOverflow: "ellipsis",
    color: (theme) => theme.palette?.text?.secondary || "grey",
  },
  cardActions: {
    padding: "1px 1px",
    borderTop: (theme) =>
      `1px solid ${theme.palette?.divider || "rgba(0,0,0,0.12)"}`,
    minHeight: "40px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  actionButton: {
    padding: "1px 2px",
    fontSize: "0.7rem",
    maxWidth: "120px",
  },
  likeButtonTextContainer: {
    display: "flex",
    alignItems: "center",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
};

export default postStyles;
